spring:
  application:
    name: EUREKA-SERVICE

#  config:
#    import: optional:configserver:http://localhost:9999
#
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false   #bcz i don't want ot register eureka server itself on eureka server
    fetch-registry: false   #1️⃣ Iska matlab hai ye service dusri services ki list Eureka se fetch nahi karegi.

